apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jovies-dev

resources:
  - ../../base
  - resourcequota.yaml
  - namespace.yaml

commonLabels:
  environment: development

# 이미지 태그 설정
images:
  - name: ghcr.io/mayne0213/jovies
    newTag: develop-sha-52e5c93d49c69b4097f048479693ccc87699ed7d

patchesStrategicMerge:
  - deployment-patch.yaml
